jobs:
- job: Deploy
  displayName: "Deploy RM Azure Functons"
  environment: $
  steps:
  - task: AzureFunctionApp@1
    displayName: Release package to Azure Funcion App
    inputs:
      azureSubscription: $
      appType: functionApp
      appName: $
      resourceGroupName: $
      package: $(System.DefaultWorkingDirectory)