jobs:
- job: 'Build'
  displayName: 'Build Java Azure functions'
  pool:
    vmImage: ubuntu-16.04
  steps:
  - checkout: self
  - task: Maven@3
    displayName: Maven pom.xml
    inputs:
      mavenPOMFile: $(BuildParameters.mavenPOMFile)
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.jar'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
