trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "Build"
    displayName: "Build the function app"
    jobs:
      - job: "Build"
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: $(system.defaultworkingdirectory)/pom.xml
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.8"
              jdkArchitectureOption: "x64"
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: "package"

          # to deploy to your app service
          - task: CopyFiles@2
            displayName: Copy Files
            inputs:
              SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/ximalia-api-functions
              Contents: "**"
              TargetFolder: $(build.artifactstagingdirectory)

  - stage: "Dev"
    displayName: "Deploy function app to dev env"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: Dev
        variables:
          - group: release
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: Azure Function App deploy
                  inputs:
                    azureSubscription: Azure_Development_Support_Plan
                    appType: functionApp
                    appName: $(FuncAppDevName)
                    resourceGroupName: $(resourceGroupName)
                    package: $(build.artifactstagingdirectory)
                    deploymentMethod: zipDeploy

  - stage: "Test"
    displayName: "Deploy function app to test env"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: Test
        variables:
          - group: release
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: Azure Function App deploy
                  inputs:
                    azureSubscription: Azure_Development_Support_Plan
                    appType: functionApp
                    appName: $(FuncAppTestName)
                    resourceGroupName: $(resourceGroupName)
                    package: $(build.artifactstagingdirectory)
                    deploymentMethod: zipDeploy

  - stage: "Staging"
    displayName: "Deploy function app to staging env"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: Staging
        variables:
          - group: release
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: Azure Function App deploy
                  inputs:
                    azureSubscription: Azure_Development_Support_Plan
                    appType: functionApp
                    appName: $(FuncAppStageName)
                    resourceGroupName: $(resourceGroupName)
                    package: $(build.artifactstagingdirectory)
                    deploymentMethod: zipDeploy
